import React from "react";

export const Two = () => {
    // Problem 2
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    const solutionTwo = () => {
        const upperLimit = 4000000;
        let fibonacciArray = [1, 2];
        for (
            let i = 3;
            i <= upperLimit;
            i += fibonacciArray[fibonacciArray.length - 2]
        ) {
            fibonacciArray.push(i);
        }
        return fibonacciArray.reduce(
            (a, b) => (b % 2 === 0 ? a + b : a + 0),
            0
        );
    };

    return (
        <div>
            Solution Two: <span className="Solutions">{solutionTwo()}</span>
        </div>
    );
};
